#!/bin/bash

START_DIR=$(pwd)
# Turn the last argument (the file name) into an absolute path
SOURCE_FILE_PATH=${@: -1}
ABSOLUTE_FILE_PATH=$(cd $(dirname $SOURCE_FILE_PATH) && pwd)/$(basename $SOURCE_FILE_PATH)
NAME_WITHOUT_EXTENSION=$(basename $ABSOLUTE_FILE_PATH .ob)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
BUILDDIR=$PARENTDIR/build
COMPILERDIR=$PARENTDIR/compiler

CC=${CC:-cc}
CXX=${CXX:-g++}
EXTRA_CFLAGS=${EXTRA_CFLAGS:-}
EXT=.c
CSTDFLAGS=-std=c17
OCFLAGS=
inSwitches=1

cp $PARENTDIR/base/runtime.c $BUILDDIR/runtime.c

while [ $inSwitches -eq 1 ]; do
  if [ $1 = "-extra_runtime" ]; then
    shift
    cat $1 >> $BUILDDIR/runtime.c
    shift
  elif [ $1 = "-cpp" ]; then
    CC=$CXX
    EXT=.cpp
    OCFLAGS="$OCFLAGS -cpp"
    CSTDFLAGS=
    shift
  elif [ $1 = "-bounds" ]; then
    OCFLAGS="$OCFLAGS -bounds"
    shift
  elif [ $1 = "-use_int64" ]; then
    OCFLAGS="$OCFLAGS -use_int64"
    shift
  elif [ $1 = "-use_double" ]; then
    OCFLAGS="$OCFLAGS -use_double"
    shift
  else
    inSwitches=0
  fi
done

cd $PARENTDIR
C_FILE=$BUILDDIR/$NAME_WITHOUT_EXTENSION$EXT
DEST_BIN=$BUILDDIR/$NAME_WITHOUT_EXTENSION
$BUILDDIR/oberon $OCFLAGS $ABSOLUTE_FILE_PATH > $C_FILE && $CC -g $CSTDFLAGS -Wall -Wextra -Wpedantic -Wno-unused-parameter -o $DEST_BIN $C_FILE $EXTRA_CFLAGS
