#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
BUILDDIR=$PARENTDIR/build
COMPILERDIR=$PARENTDIR/compiler
PERR=$COMPILERDIR/perr.py

cp $COMPILERDIR/*.ob $BUILDDIR
cp $COMPILERDIR/runtime.c $BUILDDIR
cp *.ob $BUILDDIR

CC=${CC:-cc}
CXX=${CXX:-g++}
EXTRA_CFLAGS=${EXTRA_CFLAGS:-}
EXT=.c
CSTDFLAGS=-std=c17
OCFLAGS=
inSwitches=1

while [ $inSwitches -eq 1 ]; do
  if [ $1 = "-extra_runtime" ]; then
    shift
    cat $COMPILERDIR/runtime.c $1 > $BUILDDIR/runtime.c
    shift
  elif [ $1 = "-cpp" ]; then
    CC=$CXX
    EXT=.cpp
    OCFLAGS="$OCFLAGS -cpp"
    CSTDFLAGS=
    shift
  elif [ $1 = "-bounds" ]; then
    OCFLAGS="$OCFLAGS -bounds"
    shift
  else
    inSwitches=0
  fi
done

cd $BUILDDIR
./oberon $OCFLAGS $1 | $PERR
./oberon $OCFLAGS $1 > out$EXT && $CC -g $CSTDFLAGS -Wall -Wextra -Wpedantic -Wno-unused-parameter -o out.prg out$EXT $EXTRA_CFLAGS
